query GET_PAGE_BY_DEV_ID($devId: String) {
    pages(
        where: {
            metaQuery: {
                metaArray: [
                    { key: "developer_id", value: $devId, compare: EQUAL_TO }
                ]
            }
        }
        first: 1
    ) {
        pageInfo {
            hasPreviousPage
            hasNextPage
            endCursor
        }
        edges {
            node {
                id
                pageId
                title
                content
                date
                slug
                uri
                childPages {
                    nodes {
                        id
                        title
                        slug
                    }
                }
                ancestors {
                    __typename
                }
            }
        }
    }
}
