query GET_PAGE_CHILDREN {
    pages {
        edges {
            node {
                id
                title
                slug
                date
                childPages {
                    nodes {
                        id
                        title
                        slug
                    }
                }
            }
        }
    }
}
