query GET_PAGE_BY_DEV_ID($devId: String) {
    pages(
        where: {
            metaQuery: {
                metaArray: [
                    { key: "developer_id", value: $devId, compare: EQUAL_TO }
                ]
            }
        }
        first: 1
    ) {
        pageInfo {
            hasPreviousPage
            hasNextPage
            endCursor
        }
        edges {
            node {
                id
                pageId
                title
                content
                date
                slug
                uri
                featuredImage {
                    ...featuredAttachment
                }
                childPages {
                    nodes {
                        id
                        title
                        slug
                        featuredImage {
                            ...featuredAttachment
                        }
                    }
                }
                ancestors {
                    __typename
                }
            }
        }
    }
}

fragment featuredAttachment on MediaItem {
    id
    sourceUrl
    caption
    mediaDetails {
        file
        height
        width
        meta {
            caption
            credit
            title
        }
    }
}
