# Query settings
query GET_SETTINGS {
    generalSettings {
        dateFormat
        description
        email
        language
        startOfWeek
        timeFormat
        timezone
        title
        url
    }
}
